<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventInformationsSeeder extends Seeder{

    public function run(): void{
        DB::table('event_informations')->truncate();
        DB::table('event_informations')->insert([
            [
                'bride_name' => 'Linda Johnson',
                'groom_name' => 'John Smith',
                'bride_mother_name' => 'Mary Anderson',
                'bride_father_name' => 'David Johnson',
                'groom_mother_name' => 'Susan Wilson',
                'groom_father_name' => 'Michael Smith',
                'cover_image' => 'default.jpg',
                'date_event' => '2023-10-15',
                'guests' => 'Brown, Patrick, Zuckerberg',
                'account_number' => '1234567890',
                'account_holder_name' => 'John Smith',
                'quotes' => '"A successful marriage requires falling in love many times, always with the same person." - Mignon McLaughlin',
                'address' => '123 Main Street, Cityville',
                'building_name' => 'Cityville Events Center',
            ],
            [
                'bride_name' => 'Sarah Davis',
                'groom_name' => 'Robert Brown',
                'bride_mother_name' => 'Jennifer Davis',
                'bride_father_name' => 'William Davis',
                'groom_mother_name' => 'Karen Brown',
                'groom_father_name' => 'Richard Brown',
                'cover_image' => 'default.jpg',
                'date_event' => '2023-11-20',
                'guests' => 'Brown, Patrick, Zuckerberg',
                'account_number' => '9876543210',
                'account_holder_name' => 'Robert Brown',
                'quotes' => '"Marriage is not a noun; its a verb. It isnt something you get. Its something you do. Its the way you love your partner every day." - Barbara De Angelis',
                'address' => '456 Elm Street, Townsville',
                'building_name' => 'Townsville Banquet Hall',
            ],
            [
                'bride_name' => 'Jessica White',
                'groom_name' => 'Daniel Clark',
                'bride_mother_name' => 'Karen White',
                'bride_father_name' => 'John White',
                'groom_mother_name' => 'Deborah Clark',
                'groom_father_name' => 'Steven Clark',
                'cover_image' => 'default.jpg',
                'date_event' => '2024-02-12',
                'guests' => 'Brown, Patrick, Zuckerberg',
                'account_number' => '5555555555',
                'account_holder_name' => 'Daniel Clark',
                'quotes' => '"A great marriage is not when the "perfect couple" comes together. It is when an imperfect couple learns to enjoy their differences." - Dave Meurer',
                'address' => '789 Oak Avenue, Villagetown',
                'building_name' => 'Villagetown Manor',
            ],
            [
                'bride_name' => 'Melissa Martinez',
                'groom_name' => 'Jose Rodriguez',
                'bride_mother_name' => 'Maria Martinez',
                'bride_father_name' => 'Carlos Martinez',
                'groom_mother_name' => 'Ana Rodriguez',
                'groom_father_name' => 'Luis Rodriguez',
                'cover_image' => 'default.jpg',
                'date_event' => '2024-04-30',
                'guests' => 'Brown, Patrick, Zuckerberg',
                'account_number' => '1111222233',
                'account_holder_name' => 'Jose Rodriguez',
                'quotes' => '"The best thing to hold onto in life is each other." - Audrey Hepburn',
                'address' => '101 Pine Lane, Sunnyside',
                'building_name' => 'Sunnyside Community Center',
            ],
            [
                'bride_name' => 'Emily Wilson',
                'groom_name' => 'James Thompson',
                'bride_mother_name' => 'Laura Wilson',
                'bride_father_name' => 'Mark Wilson',
                'groom_mother_name' => 'Patricia Thompson',
                'groom_father_name' => 'Robert Thompson',
                'cover_image' => 'default.jpg',
                'date_event' => '2024-06-15',
                'guests' => 'Brown, Patrick, Zuckerberg',
                'account_number' => '9999888877',
                'account_holder_name' => 'James Thompson',
                'quotes' => '"A happy marriage is a long conversation which always seems too short." - André Maurois',
                'address' => '222 Maple Street, Lakeside',
                'building_name' => 'Lakeside Grand Hotel',
            ],
            [
                'bride_name' => 'Rachel Anderson',
                'groom_name' => 'Thomas Baker',
                'bride_mother_name' => 'Susan Anderson',
                'bride_father_name' => 'Richard Anderson',
                'groom_mother_name' => 'Catherine Baker',
                'groom_father_name' => 'William Baker',
                'cover_image' => 'default.jpg',
                'date_event' => '2024-08-10',
                'guests' => 'Brown, Patrick, Zuckerberg',
                'account_number' => '7777666677',
                'account_holder_name' => 'Thomas Baker',
                'quotes' => '"Marriage is the golden ring in a chain whose beginning is a glance and whose ending is eternity." - Kahlil Gibran',
                'address' => '567 Oakwood Drive, Riverside',
                'building_name' => 'Riverside Gardens',
            ],
            ]);
    }
}